# Generated by Django 5.2.9 on 2026-03-03 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('netbox_load_balancing', '0006_healthmonitor_owner_lbservice_owner_listener_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lbserviceassignment',
            name='assigned_object_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(models.Q(('app_label', 'netbox_load_balancing'), ('model', 'virtualip')), models.Q(('app_label', 'dcim'), ('model', 'device')), models.Q(('app_label', 'virtualization'), ('model', 'virtualmachine')), models.Q(('app_label', 'dcim'), ('model', 'virtualdevicecontext')), _connector='OR')), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='memberassignment',
            name='assigned_object_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(models.Q(('app_label', 'netbox_load_balancing'), ('model', 'pool')), models.Q(('app_label', 'netbox_load_balancing'), ('model', 'healthmonitor')), _connector='OR')), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='virtualippoolassignment',
            name='assigned_object_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(models.Q(('app_label', 'ipam'), ('model', 'iprange')), models.Q(('app_label', 'ipam'), ('model', 'prefix')), models.Q(('app_label', 'ipam'), ('model', 'vlan')), _connector='OR')), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
