# Generated by Django 6.1 on 2026-09-29 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "netbox_load_balancing",
            "0008_alter_healthmonitor_owner_alter_lbservice_owner_and_more",
        ),
        ("tenancy", "0026_consolidate_unique_constraints"),
    ]

    operations = [
        migrations.AddField(
            model_name="healthmonitor",
            name="_config_context_data",
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="healthmonitor",
            name="_config_context_generation",
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="healthmonitor",
            name="local_context_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="healthmonitor",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_related",
                to="tenancy.tenant",
            ),
        ),
        migrations.AddField(
            model_name="lbservice",
            name="_config_context_data",
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="lbservice",
            name="_config_context_generation",
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="lbservice",
            name="local_context_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="listener",
            name="_config_context_data",
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="listener",
            name="_config_context_generation",
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="listener",
            name="local_context_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="listener",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_related",
                to="tenancy.tenant",
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="_config_context_data",
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="_config_context_generation",
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="member",
            name="local_context_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_related",
                to="tenancy.tenant",
            ),
        ),
        migrations.AddField(
            model_name="pool",
            name="_config_context_data",
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="pool",
            name="_config_context_generation",
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="pool",
            name="local_context_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pool",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_related",
                to="tenancy.tenant",
            ),
        ),
        migrations.AddField(
            model_name="virtualip",
            name="_config_context_data",
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="virtualip",
            name="_config_context_generation",
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="virtualip",
            name="local_context_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="virtualip",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_related",
                to="tenancy.tenant",
            ),
        ),
        migrations.AddField(
            model_name="virtualippool",
            name="_config_context_data",
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="virtualippool",
            name="_config_context_generation",
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="virtualippool",
            name="local_context_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
